services:  # <--- 你之前少了这一行！所有的容器定义都必须在 services 下面
  python-app:
    build: ./python-app
    volumes:
      - ./python-app:/app
      - ./logs/python:/app/logs
    environment:
      - FLASK_DEBUG=0
      - FLASK_APP=app.py
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - DB_HOST=db
      - MYSQL_DATABASE=${DB_NAME}
    depends_on:
      - redis
      - db

  redis:
    image: redis:alpine
    container_name: work-redis
    volumes:
      - ./redis_data:/data
    command: redis-server --appendonly yes
    restart: always

  db:
    image: mariadb:10.6
    container_name: work-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - ./mysql_data:/var/lib/mysql
