services: 

  nginx:
    image: nginx:latest
    container_name: work-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      # [新增] 把项目里的 html 文件夹挂载到 Nginx 的默认网站目录
      - ./html:/usr/share/nginx/html
    depends_on:
      - python-app
  python-app:
    build: ./python-app
    volumes:
      - ./python-app:/app
      - ./logs/python:/app/logs
    environment:
      - FLASK_DEBUG=0
      - FLASK_APP=app.py
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - DB_HOST=db
      - MYSQL_DATABASE=${DB_NAME}
    depends_on:
      - redis
      - db

  redis:
    image: redis:alpine
    container_name: work-redis
    volumes:
      - /home/pinna/my_prod_data/redis_data:/data        #（新增了安全文件存放位置）
    command: redis-server --appendonly yes
    restart: always

  db:
    image: mariadb:10.6
    container_name: work-mysql
    environment:
      # 同时设置这两个，确保万无一失
      MARIADB_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

      MARIADB_DATABASE: ${DB_NAME}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - /home/pinna/my_prod_data/mysql_data:/var/lib/mysql  #（新增了安全文件存放位置）
    restart: always
